POST /Tasks HTTP/1.1
Host: backup-manager.dormsoftware.ir
Content-Type: application/json
Content-Length: 232

{
  "Name" : "backup cms_production",
  "offset": 14000,
  "host" : "postgres-production-svc",
  "port" : 5432,
  "username" : "arvan",
  "password" : "1234567890090987654321234567",
  "db" : "cms_production"
}


x