version: '3.8'

services:
  backup-manager:
    image: backup-manager:latest # Replace with your image name
    container_name: backup-manager
    environment:
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      BACKUP_DB_USER: ${BACKUP_DB_USER}
      BACKUP_DB_PASSWORD: ${BACKUP_DB_PASSWORD}
      BACKUP_DB_HOST: ${BACKUP_DB_HOST}
      BACKUP_DB_PORT: ${BACKUP_DB_PORT}
      BACKUP_DB_NAME: ${BACKUP_DB_NAME}
    ports:
      - "8082:8080"
#    volumes:
#      - ./data:/app/data # Example volume for storing backup files, modify as needed
    restart: unless-stopped
